### ISSUE TITLE
Web.net conference 2015

### ISSUE THREAD

**Issue by GianniBortoloBossini** [imperugo/feedback#1]
Ciao,
ti scrivo in quanto organizzatore della precedente edizione della Web.Net Conference.
Volevo chiederti se hai qualche informazione in più sulla conferenza. Un idea della presunta data, della location e di quando si apriranno le iscrizioni?
Mi spiacerebbe venire a sapere delle conf troppo tardi e di non riuscire ad acquistare i biglietti.
Grazie 
Buona giornata
Ciao
Gianni

**Comment by imperugo** [comment]
Ciao @GianniBortoloBossini 
spero di annunciare a breve la data. In linea di massima siamo a inizio giugno su Milano.
Per l'iscrizione, iscriviti alla new  qui http://webnextconf.eu/ delle mail prima che di aprire le iscrizioni.

Grazie
.u

**Comment by GianniBortoloBossini** [comment]
Ho provato ad iscrivermi alla newsletter, ma sia su Chrome che su Explorer
mi da il seguente errore:

[image: Immagine in linea 1]

Grazie mille....

Il giorno 16 gennaio 2015 09:51, Ugo Lattanzi notifications@github.com ha
scritto:

**Comment by imperugo** [comment]
Non vedo l'immagine. Mi sa che hai premuto comment prima che fosse finito il caricamento.
Puoi rimandarla?

**Comment by GianniBortoloBossini** [comment]
[image: Immagine in linea 1]

Il giorno 16 gennaio 2015 12:38, Ugo Lattanzi notifications@github.com ha
scritto:

**Comment by GianniBortoloBossini** [comment]
Sostanzialmente riporta un messaggio di errore ("An error occurred! Pleas
try again later."). Lo stesso messaggio lo da da almeno un paio di mesi :)

Il giorno 16 gennaio 2015 12:47, Gianni Bortolo Bossini <
bossini.gianni@gmail.com> ha scritto:

**Comment by imperugo** [comment]
Credo sia la regex di validatione della mail.
Faccio qualche prova e ti dico

.u

**Comment by GianniBortoloBossini** [comment]
Grazie... gentilissimo!

2015-01-16 14:55 GMT+01:00 Ugo Lattanzi notifications@github.com:

**Comment by imperugo** [comment]
Ciao @GianniBortoloBossini 
dovrei aver risolto. Puoi riprovare a mettere la tua mail?

Fammi sapere
Thx
.u

**Comment by GianniBortoloBossini** [comment]
User subscribed!
Thanks!!!
Buona serata
Gianni

Il giorno Dom 1 Feb 2015 15:37 Ugo Lattanzi notifications@github.com ha
scritto:

**Comment by imperugo** [comment]
Ottimo ;)

**Comment by GianniBortoloBossini** [comment]
Ho vinto un biglietto per la conf :-D

Il giorno Dom 1 Feb 2015 22:22 Ugo Lattanzi notifications@github.com ha
scritto:

**Comment by imperugo** [comment]
Yeahhh
