### ISSUE TITLE
Consiglio API

### ISSUE THREAD

**Issue by ladysilvia** [imperugo/feedback#2]
Ciao volevo chiederti un consiglio
vorrei usare una libreria come quella di jQuery-comments e sfruttare js per scrivere tutti i dati sul server in formato json .. puoi indicarmi qualche consiglio.. 
ho visto nel tuo articolo che usi ASP 
io uso PHP mariaDB Apache ect.. 
in questa parte del progetto per i commenti vorrei evitare il DB e usare direttamente Json
 
questa è la libreria 
https://github.com/Viima/jquery-comments

			$('#comments-container').comments({
				getUsers: function(success, error) {
					$.ajax({
						type: 'get',
						url: '/api/users/',
						success: function(userArray) {
							success(userArray)
						},
						error: error
					});
				}
			});

			$('#comments-container').comments({
				postComment: function(commentJSON, success, error) {
					$.ajax({
						type: 'post',
						url: '/api/comments/',
						data: commentJSON,
						success: function(comment) {
							success(comment)
						},
						error: error
					});
				}
			});
			Backend/API implementation
			http://viima.github.io/jquery-comments/#link-4

vorrei poter usare questo metodo .. 
grazie anticipato

**Comment by imperugo** [comment]
Ciao, 
grazier per avermi contattato.
Purtroppo (forse per fortuna) non uso più jQuery da diversi anni, quindi non so darti un'aiuto su questo.

Quello che posso dirti è che, se non vuoi persistere sul db i commenti e vuoi appoggiarti a qualcosa di leggero, puoi usare un servizio esterno come Disqus o Facebook comments.

In questo caso non devi far altro che embeddare un JS nella tua pagina, il resto lo fa il servizio esterno.
Oltre ad essere gratuito come servizio, hai anche ottimi benefici perchè hai una dashboard amministrativa dei commenti, anti spam, rating e molto altro ancora.

Ciauz

**Comment by ladysilvia** [comment]
Grazie per aver risposto.. ho risolto il problema usando Json-server.. mi sono rimasti alcuni problemi minori, come quello degli allegati nei commenti e il voto espresso come like.. 
nel mio progetto non ha senso usare i plugin di Facebook o di altre piattaforme. 
Se hai consigli su come gestire gli allegati e il like del singolo utente.. scrivimi 

Grazie 
Silvia
